#!/bin/bash

BIL=Nissan

echo $BIL # blir echo Nissan --> skriver ut på stdout: Nissan

echo ${BIL} # blir echo Nissan --> skriver ut på stdout: Nissan

# Stora bokstäver --> NISSAN
echo ${BIL^^}

#
echo Bilmärket 
