#!/bin/bash

BIL=Nissan

echo $BIL # blir echo Nissan --> skriver ut på stdout: Nissan

echo ${BIL} # blir echo Nissan --> skriver ut på stdout: Nissan

# Stora bokstäver --> NISSAN
echo ${BIL^^}

# Längd
echo Bilmärket ${BIL}s längd är ${#BIL}

# Se tre tecken, från tecken nummer 2
echo Delen blev: ${BIL:3}
