#!/bin/bash

SUFFIX="san"

len() {
    # Argumenten fås med $1, $2, $3, ...
    # Antal argument fås med $#
    # Byt ut argument mot delar inom fnuttar: "$@" ==> "$1" "$2" ..
    echo "SUFFIX: $SUFFIX"
    echo "${#1}"
}

echo -n "Skriv ditt namn: "
read -r NAME

echo "Hi $NAME"
echo "Your name has $(len "$NAME") letters"

