#!/bin/bash

# cat

cat langfil                                                                                       # argument med filnamn
cat langfil bokstaver                                                                             # det kan vara flera också, allt slås ihop
echo Hej | cat                                                                                    # många kommandon lyssnar på stdin om de inte får filnamn
echo Hej | cat | cat | cat | cat                                                                  # mer meningslöst
echo -e 'Hej!\n\nDu har vunnit en miljon, sätt endast in överföringspengar\n\nMvh, Kent' | cat -n # få radnummer
# head
# tail
# sort
# uniq
# cut
# tr
