#!/bin/bash

# Kallals i "folkmun" för globbing.

# * betyder "vad som helst eller ingenting"
ls *sol.png

# ? betyder "exakt EN av vad VAD SOM HELST (förutom ingenting)"
ls -l ???.png
ls -l ????????*

# [abc] tecknet måste vara exakt ett av a, b och c
ls instruktion[345].jpg
instruktion3.jpg instruktion4.jpg instruktion5.jpg

$ ls instruktion[!345].jpg
instruktion1.jpg instruktion6.jpg instruktion8.jpg
instruktion2.jpg instruktion7.jpg instruktion9.jpg
