#!/bin/bash

# * betyder "vad som helst eller ingenting"
ls *sol.png

# ? betyder "exakt EN av vad VAD SOM HELST (förutom ingenting)"
ls -l ???.png
ls -l ????????*


ls instruktion[345].jpg
instruktion3.jpg  instruktion4.jpg  instruktion5.jpg
