#!/bin/bash

# first_row - prints the first row in a file
#
# Usage:
#   first_row FILE
#

if [ "$#" -ne 1 ]; then
	echo "ERROR: Pass exactly one FILE" >&2
	exit 1 # Allt utom 0 = fel
fi

head -n 1 

echo antal args: $#
