#!/bin/bash

# Formen är: kommando n> utfil

echo "Utmatning till stdout... rad 5 till fil" >stdout_inget_n_skriv_over1
echo "Utmatning till stdout... rad 6 till fil" 1>stdout_inget_n_skriv_over2

echo "Utmatning till stdout... till fil" >>stdout_inget_n_addera
echo "Utmatning till stdout... till fil" 1>>stdout_inget_n__addera
