#!/bin/bash

# Segt! Kör sekvensiellt, tar ca 200 sekunder

#./intense
# ./intense
# ./intense
# ./intense
# ./intense
# ./intense
# ./intense
# ./intense
# ./intense
# ./intense

./intense &
./intense &
./intense &
./intense &
./intense &
./intense &
./intense &
./intense &
./intense &
./intense &
wait

# Kod som körs efter all processning ovan följer...
