#!/bin/bash

# Remove Repeating Prefixes

file=$1
dest=$file.rrp
prefix_len=1
max=5

while IFS= read -r line; do
	prefix=${line:0:prefix_len}
	if [ "$prefix" != "$old_prefix" ]; then
		count=1
	else
		(( count++ ))
	fi
	if [ "$count" == "$max" ]; then
		echo "..."
	elif [ "$count" -gt "$max" ]; then
		:
	else
		echo "$line"
	fi
	old_prefix=$prefix
done < "$1" > "$dest"
