#!/bin/bash

MINNE=apple

# Parentes = Ny barnprocess via "fork", kopia av variabler och allt annat
foo() (
    echo Inner eat 1 "$MINNE"
    MINNE=banan
    echo Inner eat 2 "$MINNE"
)

foo

echo Outer eat "$MINNE"
