#!/bin/bash

# Parentes = Ny barnprocess via "fork", kopia av variabler och allt annat
(
    sleep 5 # Vi fakar att vi laddar ned en iso fil
    echo ISO DOWNLOAD COMPLETE
) &

read -p "Vad heter du? " NAMN
echo "Hej $NAMN"
