#!/bin/bash

# Pipe = Output från ett kommando -> Input till nästa kommando
echo -e "$RANDOM\n$RANDOM\n$RANDOM\n$RANDOM" | sort -g | tail -n 1

# Pipes exitstatus är sista kommandots status
$ echo hej | grep h
hej
ITINF25/lektion8/aterblick/3. redirections
$ echo $?
0

