#!/bin/bash

source $HOME/Documents/l1-live/DEVOPS25/lektion8/import_relprob/len_prob_import.sh

echo "RELPROB på 'import' i Bash"
echo -n "Skriv ditt namn: "
read -r NAME

echo "Hi $NAME"
echo "Your name has $(len "$NAME") letters"
