#!/bin/bash

SCRIPT_DIR=$(cd $(dirname $0) && pwd)

exit # INTE ÄN

echo "RELPROB på 'import' i Bash"
echo -n "Skriv ditt namn: "
read -r NAME

echo "Hi $NAME"
echo "Your name has $(len "$NAME") letters"
