#!/bin/bash

$ echo x{a,b,c}y
xay xby xcy

$ echo x{hopp,kaka,baka}y
xhoppy xkakay xbakay

$ echo x{hopp,kaka,}y
xhoppy xkakay xy

# Serie (kortare skrivsätt)

touch bokf20{25..30}.txt

touch "mjolnerbacken "{1..22}{a,b}.txt

touch 'den har fulen har ett valdigt langt namn som ar jobbigt att skriva.txt'
# Fixas med brace expansion, första gången u, andra gången i
mv "den har f"{u,i}"len har ett valdigt langt namn som ar jobbigt att skriva.txt"
