#!/bin/bash

# \( \) utan -E. Vi kör med -E då det är mer lättläst.
# ( ) med -E.

# grep -E 'stork' wikipedia.txt
# grep -E 'stork|animal' wikipedia.txt
# grep --color -E '[0-9]+' wikipedia.txt
# grep --color -E '[0-9]+|stork' wikipedia.txt
# grep --color -E '... | ... ' wikipedia.txt  # Klurig! Hur matcha ord på tre tecken?
# grep -o -E '[0-9]+' wikipedia.txt
grep --color -E
