#!/bin/bash

# Angränsande

# grep för alla rader med short options, optioner med ett tecken, så inte --version men -v
# man ls | grep -E -A 1 -- '^ +-[a-zA-Z]'

# -A n visar n rader efter träffen
man ls | grep -E -A 2 -- '^ +-[a-zA-Z]'
