#!/bin/bash

# Sök rekursivt bland alla filer i ett filträd med -r

# Alla rader
# grep -E -r '[^A-Z][A-Z]{2,}[^A-Z]' ../../extext/

# Visa endast träffarna
grep -E -o -r '[^A-Z][A-Z]{2,}[^A-Z]' ../../extext/
