#!/bin/bash

# Funktioner som körs i en barn-bash, en subshell, har
# parenteser istället för måsvingar.

HALSNING=Wilkommen
sub_greet() (
    namn1="$1"
    namn2="$2"
    echo "$HALSNING ${namn1}san och ${namn2}san"
    return 1
)

sub_greet Molle Peter

echo "namn1 efter: $namn1"

echo SISTA RADEN
