#!/bin/bash

# dirigera om.. STDOUT .. till en fil

# En pil ersätter
$ echo CONTENT 1>stdout1
$ echo CONTENT >stdout2

# Två pilar lägger till
echo EN TILL RAD >>stdout1

# dirigera om.. STDERR .. till en fil

grep toyota bilar.txt > 
