#!/bin/bash

# Använda variabln NF för variabelt antal fält. Det kan vara bra
# för att t.ex. skriva ut sista fältet.

# awk -F ';' '{ print $(NF) }' ../../extext/variabelt_antal_falt.csv
# awk -F ';' '{ print $(NF - 0) }' ../../extext/variabelt_antal_falt.csv

awk -F ';' '{ print $(NF - 1) }' ../../extext/variabelt_antal_falt.csv
