#!/bin/bash

# Se träffens hela rad - det är standardbeteendet så vi behöver ingen särskilt option för det

# cat ../../extext/richard.txt | grep -E --color=always '(^| )[0-9]{4}'

cat ../../extext/richard.txt | grep -E --color=always '(^|[- ])[0-9]{4}'
