#!/bin/bash

# Se träffens hela rad - det är standardbeteendet så vi behöver ingen särskilt option för det

# Träff på det mesta. Motsvarar iteration 0.3
# cat ../../extext/richard.txt | grep -E --color=always '(^| )[0-9]{4}'

# Träff på det mesta. Motsvarar iteration 0.4
cat ../../extext/richard.txt | grep -E --color=always '(^|[- ])[0-9]{4}'
