#!/bin/bash

# sed - stream editor Byt ut en matching mot en sträng som innehåller en del av matchningen

# Byt ut det första ordet som börjar med sS till delordet efter första bokstaven
# Stallman -> tallman
# sed -E 's/[Ss]([^, .]+)/\1/' ../../extext/richard.txt

# Byt ut ALLA ord som börjar med sS till delordet efter första bokstaven
# Stallman Snok -> tallman nok
sed -E 's/[Ss]([^, .]+)/\1/g' ../../extext/richard.txt
