#!/bin/bash

# sed - stream editor Vänd på strängar av längd 6 så att hejsan -> sanhej

# Samma sak
# sed -E 's/([^ .,]{6})([^ .,]+)([ .,]+)/\1\2\3/g' ../../extext/linux.txt

# Samma sak
sed -E 's/([^ .,]{1,3})([^ .,]{1,3})/\2\1/g' ../../extext/linux.txt
