#!/bin/bash

while true; do
	read -r -p 'Namn (klar för att avbryta): ' namn
	if test "$namn" = "klar"; then
		break
	fi
	echo "$namn" >>namnfil
done
echo "Du skrev såhär många namn: "
wc -l "namnfil"

rm "namnfil"
