#!/bin/bash

while IFS="," read -r fornamn efternamn losenord operation; do
  echo "Value: $fornamn"
  echo "Value: $efternamn"
  echo "Value: $losenord"
  echo "Value: $operation"
done < <(tail -n +2 personer.csv)

# förnamn,efternamn,lösenord,operation
