#!/bin/bash

while IFS="," read -r fornamn efternamn losenord operation
do
  [ ! -z "$seen_header" ]
  echo "Value: $fornamn"
  echo "Value: $efternamn"
  echo "Value: $losenord"
  echo "Value: $operation"
done <personer.csv # förnamn,efternamn,lösenord,operation
